def demo_review():
    return {
        "id": "rev_ai_ticket_summarizer",
        "title": "AI Ticket Summarizer",
        "status": "CROSS_EXAMINATION",
        "riskScore": 85,
        "riskLevel": "Critical",
        "decision": "Pending Human Review",
        "findings": [
            {
                "id": "SEC-001",
                "domain": "Security",
                "severity": "critical",
                "title": "Raw support ticket payloads are logged",
                "status": "confirmed",
                "agent": "Security Review",
            },
            {
                "id": "PRIV-001",
                "domain": "Privacy",
                "severity": "high",
                "title": "Customer PII detected in ticket text",
                "status": "confirmed",
                "agent": "Privacy Compliance",
            },
            {
                "id": "QA-001",
                "domain": "QA",
                "severity": "high",
                "title": "Missing PII redaction regression test",
                "status": "open",
                "agent": "QA Test",
            },
            {
                "id": "LEGAL-001",
                "domain": "Legal",
                "severity": "medium",
                "title": "Customer-facing AI disclosure not present",
                "status": "open",
                "agent": "Legal Policy",
            },
        ],
        "events": [
            {
                "id": "1",
                "ts": "10:02",
                "type": "room_created",
                "from": "Coordinator",
                "message": "Created Band review room and recruited Engineering, Security, Privacy, QA, Decision, and Audit Scribe.",
            },
            {
                "id": "2",
                "ts": "10:04",
                "type": "risk_finding",
                "from": "Privacy Compliance",
                "severity": "high",
                "message": "Detected customer emails, order IDs, and complaint content in sample tickets.",
            },
            {
                "id": "3",
                "ts": "10:05",
                "type": "challenge",
                "from": "Privacy Compliance",
                "message": "Asked Security Review to verify whether raw prompts are logged or retained.",
            },
            {
                "id": "4",
                "ts": "10:07",
                "type": "risk_finding",
                "from": "Security Review",
                "severity": "critical",
                "message": "Found DEBUG_PAYLOADS=true and logger.debug(request.body) in launch artifacts.",
            },
            {
                "id": "5",
                "ts": "10:09",
                "type": "challenge_response",
                "from": "Engineering Readiness",
                "message": "Confirmed payload logging path is active in deployment config.",
            },
            {
                "id": "6",
                "ts": "10:10",
                "type": "risk_finding",
                "from": "QA Test",
                "severity": "high",
                "message": "No PII redaction regression test or prompt injection test found in test plan.",
            },
            {
                "id": "7",
                "ts": "10:11",
                "type": "decision_recommendation",
                "from": "Decision Arbiter",
                "message": "Risk score raised to 85. Human escalation required before launch.",
            },
        ],
    }