from __future__ import annotations

from app.services.store import get_review


def build_dossier_markdown(review_id: str = "rev_ai_ticket_summarizer") -> str:
    review = get_review(review_id)

    findings = review.get("findings", [])
    remediations = review.get("remediations", [])
    approvals = review.get("approvals", [])
    events = review.get("events", [])

    lines: list[str] = []

    lines.append("# LaunchGate AI Decision Dossier")
    lines.append("")
    lines.append(f"**Release:** {review.get('title', 'Unknown')}")
    lines.append(f"**Review ID:** {review.get('id', review_id)}")
    lines.append(f"**Status:** {review.get('status', 'Unknown')}")
    lines.append(f"**Decision:** {review.get('decision', 'Pending')}")
    lines.append(f"**Risk Score:** {review.get('riskScore', 0)}")
    lines.append(f"**Risk Level:** {review.get('riskLevel', 'Unknown')}")
    lines.append("")
    lines.append("---")
    lines.append("")

    lines.append("## Executive Summary")
    lines.append("")
    if review.get("decision") in ["REQUEST_CHANGES", "Request Changes"]:
        lines.append(
            "LaunchGate AI recommends **REQUEST CHANGES** before launch. "
            "The review identified critical risks involving customer PII, raw payload logging, "
            "missing AI safety tests, and incomplete disclosure/vendor-retention controls."
        )
    else:
        lines.append(
            "LaunchGate AI has generated this dossier from the agent collaboration timeline, "
            "structured findings, remediations, and approval state."
        )
    lines.append("")

    lines.append("## Findings")
    lines.append("")
    if not findings:
        lines.append("_No findings recorded._")
    else:
        for finding in findings:
            lines.append(f"### {finding.get('id')} — {finding.get('title')}")
            lines.append("")
            lines.append(f"- **Domain:** {finding.get('domain')}")
            lines.append(f"- **Severity:** {finding.get('severity')}")
            lines.append(f"- **Status:** {finding.get('status')}")
            lines.append(f"- **Source Agent:** {finding.get('agent')}")
            evidence = finding.get("evidence") or []
            if evidence:
                lines.append("- **Evidence:**")
                for item in evidence:
                    lines.append(
                        f"  - `{item.get('artifact', 'artifact')}`"
                        + (f" — {item.get('location')}" if item.get("location") else "")
                    )
            lines.append("")

    lines.append("## Required Remediations")
    lines.append("")
    if not remediations:
        lines.append("_No remediation tasks recorded._")
    else:
        for task in remediations:
            lines.append(
                f"- **{task.get('id')}** — {task.get('title')} "
                f"({task.get('severity')}, owner: {task.get('owner')}, status: {task.get('status')})"
            )
    lines.append("")

    lines.append("## Approval Matrix")
    lines.append("")
    if not approvals:
        lines.append("_No approvals recorded._")
    else:
        lines.append("| Domain | Status |")
        lines.append("|---|---|")
        for approval in approvals:
            lines.append(f"| {approval.get('domain')} | {approval.get('status')} |")
    lines.append("")

    lines.append("## Band Collaboration Timeline")
    lines.append("")
    if not events:
        lines.append("_No timeline events recorded._")
    else:
        for event in events:
            lines.append(
                f"- **{event.get('ts')}** — `{event.get('type')}` "
                f"from **{event.get('from')}**: {event.get('message')}"
            )
    lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(
        "Generated by LaunchGate AI. Band served as the agent collaboration layer for "
        "multi-agent review, structured handoff, cross-functional risk analysis, and audit traceability."
    )

    return "\n".join(lines)
